DropDownDataJSON =
{
    "QuestionText" : "<b>Soru:</b> 16.01.20XX tarihinde işletme bankaya verdiği talimatla nominal değeri 1,075 TL olan hisse senetlerinde 2.000 satın almıştır.",
    "Assessment": [
        "",
        "100. Kasa",
        "101. Alınan Çekler",
        "102. Bankalar",
        "103. Verilen Çekler Ve Ödeme Emirleri(-)",
        "108. Diğer Hazır Değerler",
        "110. Hisse Senetleri",
        "111. Özel Kesim Tahvil Senet Ve Bonoları",
         "112. Kamu Kesimi Tahvil, Senet Ve Bonoları",
        "118. Diğer Menkul Kıymetler",
        "119. Menkul Kıymetler Değer Düşüklüğü Karşılığı(-)",
        "120. Alıcılar",
        "121. Alacak Senetleri",
        "122. Alacak Senetleri Reeskontu(-)",
        "126. Verilen Depozito Ve Teminatlar",
        "127. Diğer Ticari Alacaklar",
        "128. Şüpheli Ticari Alacaklar",
        "129. Şüpheli Ticari Alacaklar Karşılığı(-)",
        "131. Ortaklardan Alacaklar",
        "132. İştiraklerden Alacaklar",
        "133. Bağlı Ortaklıklardan Alacaklar",
        "135. Personelden Alacaklar",
        "136. Diğer Çeşitli Alacaklar",
        "137. Diğer Alacak Senetleri Reeskontu(-)",
        "138. Şüpheli Diğer Alacaklar",
        "139. Şüpheli Diğer Alacaklar Karşılığı(-)",
        "150. İlk Madde Malzeme",
        "151. Yarı Mamuller",
        "152. Mamuller",
        "153. Ticari Mallar",
        "157. Diğer Stoklar",
        "158. Stok Değer Düşüklüğü Karşılığı(-)",
        "159. Verilen Sipariş Avansları",
        "170. Yıllara Yaygın İnşaat Ve Onarım Maliyetleri",
        "179. Taşeronlara Verilen Avanslar",
        "180. Gelecek Aylara Ait Giderler",
        "181. Gelir Tahakkukları",
        "190. Devreden KDV",
        "191. İndirilecek KDV",
        "192. Diğer KDV",
        "193. Peşin Ödenen Vergiler Ve Fonlar",
        "195. İş Avansları",
        "196. Personel Avansları",
        "197. Sayım Ve Tesellüm Noksanları",
        "198. Diğer Çeşitli Dönen Varlıklar",
        "199. Diğer Dönen Varlıklar Karşılığı(-)",
        "220. Alıcılar",
        "221. Alacak Senetleri",
        "222. Alacak Senetleri Reeskontu(-)",
        "226. Verilen Depozito Ve Teminatlar",
        "229. Şüpheli Ticari Alacaklar Karşılığı(-)",
        "231. Ortaklardan Alacaklar",
        "232. İştiraklerden Alacaklar",
        "233. Bağlı Ortaklıklardan Alacaklar",
        "235. Personelden Alacaklar",
        "236. Diğer Çeşitli Alacaklar",
        "237. Diğer Alacak Senetleri Reeskontu(-)",
        "239. Şüpheli Diğer Alacaklar Karşılığı(-)",
        "240. Bağlı Menkul Kıymetler",
        "241. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı(-)",
        "242. İştirakler",
        "243. İştiraklere Sermaye Taahhütleri(-)",
        "244. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı(-)",
        "245. Bağlı Ortaklıklar",
        "246. Bağlı Ortaklıklara Sermaye Taahhütleri(-)",
        "247. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı(-)",
        "248. Diğer Mali Duran Varlıklar",
        "249. Diğer Mali Duran Varlıklar Karşılığı(-)",
        "250. Arazi Ve Arsalar",
        "251. Yer Altı Ve Yer Üstü Düzenleri",
        "252. Binalar",
        "253. Tesis, Makine Ve Cihazlar",
        "254. Taşıtlar",
        "255. Demirbaşlar",
        "256. Diğer Maddi Duran Varlıklar",
        "257. Birikmiş Amortismanlar(-)",
        "258. Yapılmakta Olan Yatırımlar",
        "259. Verilen Avanslar",
        "260. Haklar",
        "261. Şerefiye",
        "262. Kuruluş Ve Örgütlenme Giderleri",
        "263. Araştırma Ve Geliştirme Giderleri",
        "264. Özel Maliyetler",
        "267. Diğer Maddi Olmayan Duran Varlıklar",
        "268. Birikmiş Amortismanlar(-)",
        "269. Verilen Avanslar",
        "271. Arama Giderleri",
        "272. Hazırlık Ve Geliştirme Giderleri",
        "277. Diğer Özel Tükenmeye Tabi Varlıklar",
        "278. Birikmiş Tükenme Payları(-)",
        "279. Verilen Avanslar",
        "280. Gelecek Yıllara Ait Giderler",
        "281. Gelir Tahakkukları",
        "291. Gelecek Yıllarda İndirilecek KDV",
        "292. Diğer KDV",
        "293. Gelecek Yıllar İhtiyacı Stoklar",
        "294. Elden Çıkarılacak Stoklar Ve Maddi Duran Varlıklar",
        "295. Peşin Ödenen Vergi Ve Fonlar",
        "297. Diğer Çeşitli Duran Varlıklar",
        "298. Stok Değer Düşüklüğü Karşılığı(-)",
        "299. Birikmiş Amortismanlar(-)",
        "300. Banka Kredileri",
        "303. Uzun Vadeli Kredilerin Anapara Taksitleri Ve Faizleri",
        "304. Tahvil Anapara Borç, Taksit Ve Faizleri",
        "305. Çıkarılan Bonolar Ve Senetler",
        "306. Çıkarılmış Diğer Menkul Kıymetler",
        "308. Menkul Kıymetler İhraç Farkı(-)",
        "309. Diğer Mali Borçlar",
        "320. Satıcılar",
        "321. Borç Senetleri",
        "322. Borç Senetleri Reeskontu(-)",
        "326. Alınan Depozito Ve Teminatlar",
        "329. Diğer Ticari Borçlar",
        "331. Ortaklara Borçlar",
        "332. İştiraklere Borçlar",
        "333. Bağlı Ortaklıklara Borçlar",
        "335. Personele Borçlar",
        "336. Diğer Çeşitli Borçlar",
        "337. Diğer Borç Senetleri Reeskontu(-)",
        "340. Alınan Sipariş Avansları",
        "349. Alınan Diğer Avanslar",
        "350,358 Yıllara Yaygın İnşaat Ve Onarım Hakedişleri Bedelleri",
        "360. Ödenecek Vergi Ve Fonlar",
        "361. Ödenecek Sosyal Güvenlik Kesintileri",
        "368. Vadesi Geçmiş, Ertelenmiş Veya Taksitlendirilmiş Vergi Ve Diğer Yükümlülükler",
        "369. Ödenecek Diğer Yükümlülükler",
        "370. Dönem Kârı Vergi Ve Diğer Yasal Yükümlülük Karşılıkları",
        "371. Dönem Kârının Peşin Ödenen Vergi Ve Diğer Yükümlülükleri(-)",
        "372. Kıdem Tazminatı Karşılığı",
        "373. Maliyet Giderleri Karşılığı",
        "379. Diğer Borç Ve Gider Karşılıkları",
        "380. Gelecek Aylara Ait Gelirler",
        "381. Gider Tahakkukları",
        "391. Hesaplanan KDV",
        "392. Diğer KDV",
        "393. Merkez Ve Şubeler Cari Hesabı",
        "397. Sayım Ve Tesellüm Fazlaları",
        "399. Diğer Çeşitli Yabancı Kaynaklar",
        "400. Banka Kredileri",
        "405. Çıkarılmış Tahviller",
        "407. Çıkarılmış Diğer Menkul Kıymetler",
        "408. Menkul Kıymetler İhraç Farkı(-)",
        "409. Diğer Mali Borçlar",
        "420. Satıcılar",
        "421. Borç Senetleri",
        "422. Borç Senetleri Reeskontu(-)",
        "426. Alınan Depozito Ve Teminatlar",
        "429. Diğer Ticari Borçlar",
        "431. Ortaklara Borçlar",
        "432. İştiraklere Borçlar",
        "433. Bağlı Ortaklıklara Borçlar",
        "436. Diğer Çeşitli Borçlar",
        "437. Diğer Borç Senetleri Reeskontu(-)",
        "438. Kamuya Olan Ertelenmiş Veya Taksitlendirilmiş Borçlar",
        "440. Alınan Sipariş Avansları",
        "449. Alınan Diğer Avanslar",
        "472. Kıdem Tazminatı Karşılığı",
        "479. Diğer Borç Ve Gider Karşılıkları",
        "480. Gelecek Yıllara Ait Gelirler",
        "481. Gider Tahakkukları",
        "492. Gelecek Yıllara Ertelenmiş Veya Terkin Edilecek KDV",
        "493. Tesise Katılma Payları",
        "499. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar",
        "500. Sermaye",
        "501. Ödenmemiş Sermaye(-)",
        "520. Hisse Senetleri İhraç Primleri",
        "521. Hisse Senedi İptal Kârları",
        "522. Maddi Duran Varlık Yeniden Değerleme Artışları",
        "523. İştirakler Yeniden Değerleme Artışları",
        "524. Maliyet Artışları Fonu",
        "529. Diğer Sermaye Yedekleri",
        "540. Yasal Yedekler",
        "541. Statü Yedekleri",
        "542. Olağanüstü Yedekler",
        "548. Diğer Kâr Yedekleri",
        "549. Özel Fonlar",
        "570. Geçmiş Yıllar Kârları",
        "580. Geçmiş Yıllar Zararları(-)",
        "590. Dönem Net Kârı",
        "591. Dönem Net Zararı(-)",
        "600. Yurt İçi Satışlar",
        "601. Yurt Dışı Satışlar",
        "602. Diğer Gelirler",
        "610. Satıştan İadeler(-)",
        "611. Satış İndirimleri(-)",
        "612. Diğer İndirimler(-)",
        "620. Satılan Mamuller Maliyeti(-)",
        "621. Satılan Ticari Mallar Maliyeti(-)",
        "622. Satılan Hizmet Maliyeti(-)",
        "623. Diğer Satışların Maliyeti(-)",
        "630. Araştırma Ve Geliştirme Giderleri(-)",
        "631. Pazarlama Satış Ve Dağıtım Giderleri(-)",
        "632. Genel Yönetim Giderleri(-)",
        "640. İştiraklerden Temettü Gelirleri",
        "641. Bağlı Ortaklıklardan Temettü Gelirleri",
        "642. Faiz Gelirleri",
        "643. Komisyon Gelirleri",
        "644. Konusu Kalmayan Karşılıklar",
        "645. Menkul Kıymet Satış Kârları",
        "646. Kambiyo Kârları",
        "647. Reeskont Faiz Gelirleri",
        "648. Enflasyon Düzeltme Kârları",
        "649. Diğer Olağan Gelir Ve Kârlar",
        "653. Komisyon Giderleri(-)",
        "654. Karşılık Giderleri(-)",
        "655. Menkul Kıymet Satış Zararları(-)",
        "656. Kambiyo Zararları(-)",
        "657. Reeskont Faiz Giderleri(-)",
        "658. Enflasyon Düzeltmesi Zararları(-)",
        "659. Diğer Olağan Gider Ve Zararlar(-)",
        "660. Kısa Vadeli Borçlanma Giderleri(-)",
        "661. Uzun Vadeli Borçlanma Giderleri(-)",
        "671. Önceki Dönem Gelir Ve Kârları",
        "679. Diğer Olağan Dışı Gelir Ve Kârlar",
        "680. Çalışmayan Kısım Gider Ve Zararları(-)",
        "681. Önceki Dönem Gider Ve Zararları(-)",
        "689. Diğer Olağan Dışı Gider Ve Zararlar(-)",
        "690. Dönem Kârı Veya Zararı",
        "691. Dönem Kârı Vergi Ve Diğer Yasal Yükümlülük Karşılıkları(-)",
        "692. Dönem Net Kârı Veya Zararı",
        "697. Yıllara Yaygın İnşaat Ve Enflasyon Düzeltme Hesabı",
        "698. Enflasyon Düzeltme Hesabı",
        "700. Maliyet Muhasebesi Bağlantı Hesabı",
        "701. Maliyet Muhasebesi Yansıtma Hesabı",
        "710. Direkt İlk Madde Ve Malzeme Giderleri Hesabı",
        "711. Direkt İlk Madde Ve Malzeme Yansıtma Hesabı",
        "712. Direkt İlk Madde Ve Malzeme Fiyat Farkı",
        "713. Direkt İlk Madde Ve Malzeme Miktar Farkı",
        "720. Direkt İşçilik Giderleri",
        "721. Direkt İşçilik Giderleri Yansıtma Hesabı",
        "722. Direkt İşçilik Ücret Farkları",
        "723. Direkt İşçilik Süre Farkları",
        "730. Genel Üretim Giderleri",
        "731. Genel Üretim Giderleri Yansıtma Hesabı",
        "732. Genel Üretim Giderleri Bütçe Farkları",
        "733. Genel Üretim Giderleri Verimlilik Giderleri",
        "734. Genel Üretim Giderleri Kapasite Farkları",
        "740. Hizmet Üretim Maliyeti",
        "741. Hizmet Üretim Maliyeti Yansıtma Hesabı",
        "742. Hizmet Üretim Maliyeti Fark Hesapları",
        "750. Araştırma Ve Geliştirme Giderleri",
        "751. Araştırma Ve Geliştirme Giderleri Yansıtma Hesabı",
        "752. Araştırma Ve Geliştirme Gider Farkları",
        "760. Pazarlama Satış Ve Dağıtım Giderleri",
        "761. Pazarlama Satış Ve Dağıtım Giderleri Yansıtma Hesabı",
        "762. Pazarlama Satış Ve Dağıtım Giderleri Fark Hesabı",
        "770. Genel Yönetim Giderleri",
        "771. Genel Yönetim Giderleri Yansıtma Hesabı",
        "772. Genel Yönetim Gider Farkları Hesabı",
        "780. Finansman Giderleri",
        "781. Finansman Giderleri Yansıtma Hesabı",
        "782. Finansman Giderleri Fark Hesabı",
        "790. İlk Madde Ve Malzeme Giderleri",
        "791. İşçi Ücret Ve Giderleri",
        "792. Memur Ücret Ve Giderleri",
        "793. Dışarıdan Sağlanan Fayda Ve Hizmetler",
        "794. Çeşitli Giderler",
        "795. Vergi, Resim Ve Harçlar",
        "796. Amortisman Ve Tükenme Payları",
        "797. Finansman Giderleri",
        "798. Gider Çeşitleri Yansıtma Hesabı",
        "799. Üretim Maliyet Hesabı"
   ]
};